version: '3.8'

services:
  www:
    build: ./www
    # build: 
    #   context: ./dockerfile
    #   dockerfile: www.dockerfile
    image: manga-www
    container_name: ${CONTAINER_NAME:-manga-www}
    restart: always
    tty: true
    volumes:
      - ./www/.env:/app/.env
    depends_on:
      - server
    ports:
      - 127.0.0.1:3000:3000

  server:
    build: ./server
    # build: 
    #   context: ./dockerfile
    #   dockerfile: server.dockerfile
    image: manga-api
    container_name: ${CONTAINER_NAME:-manga-api}
    restart: always
    tty: true
    volumes:
      - ./server/.env:/app/.env
    ports:
      - 127.0.0.1:8000:8000