name: "Feature Request"
description: "Solicite um recurso ou aprimoramento"
labels: ["needs triage"]
body:
  - type: "markdown"
    attributes:
      value: |
        Obrigado por criar uma issue 😄!

        Somos todos voluntários aqui, então ajude-nos a ajudá-lo reservando um tempo para
        preencha com precisão este modelo.❤️
  - type: "checkboxes"
    id: "where-it-occurred"
    attributes:
      label: "Essa implementação vai ser onde?"
      description: "Marque as alternativas em que essa implemntação vai ser adicionada."
      options:
        - label: "front-end"
        - label: "back-end"
        - label: "Criar um novo serviço"
    validations:
      required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Descrição"
      description: "Descreva sua solicitação"
    validations:
      required: true
  - type: "textarea"
